package main

import (
	"html/template"
	"log"
	"net/http"
	"sort"
	"time"
)

type Track struct {
	Title  string
	Artist string
	Album  string
	Year   int
	Length time.Duration
}

// List of songs
var tracks = []*Track{
	{"Go", "Delilah", "From the Roots Up", 2012, length("3m38s")},
	{"Go", "Moby", "Moby", 1992, length("3m37s")},
	{"Go Ahead", "Alicia Keys", "As I Am", 2007, length("4m36s")},
	{"Ready 2 Go", "Martin Solveig", "Smash", 2011, length("4m24s")},
}

func length(s string) time.Duration {
	dur, err := time.ParseDuration(s)
	if err != nil {
		panic(err)
	}
	return dur
}

// what column we click
type Column int

const (
	Title Column = iota
	Artist
	Album
	Year
	Length
)

// NEW: wrapper around what will complies with Interface and passed to "sort()"
type customSort struct {
	tracks []*Track
	// every time Click() was called, we put an Order to this slice
	order []Column
}

// NEW: additional function to ADD ORDER with specific Column when user Clicks to a Column
// Note: element 0 = highest priority = most recent click
func (x *customSort) Click(col Column) {
	newOrder := []Column{col}
	for _, existing := range x.order {
		// only add if Click() calls a different function than what we currently have
		if existing != col {
			newOrder = append(newOrder, existing)
		}
	}
	x.order = newOrder
}

func (x customSort) Len() int { return len(x.tracks) }
func (x customSort) Swap(i, j int) {
	x.tracks[i], x.tracks[j] = x.tracks[j], x.tracks[i]
}

// this will run through slice of Orders that were generated by Click(); generate corresponding Less() function for each Order
func (x customSort) Less(i, j int) bool {
	a := x.tracks[i]
	b := x.tracks[j]
	for _, col := range x.order {
		switch col {
		case Title:
			if a.Title != b.Title {
				return a.Title < b.Title
			}
		case Artist:
			if a.Artist != b.Artist {
				return a.Artist < b.Artist
			}
		case Album:
			if a.Album != b.Album {
				return a.Album < b.Album
			}
		case Year:
			if a.Year != b.Year {
				return a.Year < b.Year
			}
		case Length:
			if a.Length != b.Length {
				return a.Length < b.Length
			}
		}
	}
	return false
}

var sorter = customSort{
	tracks: tracks,
}

// "." is the argument we pass in page.Execute() i.e tracks (the []*Track)
var page = template.Must(template.New("tracks").Parse(`
	<html>
	<body>
		<h2>Tracks</h2>
		<p>Click a column header to sort.</p>
		<table border="1" cellpadding="5">
			<tr>
				<th><a href="/?sort=title">Title</a></th>
				<th><a href="/?sort=artist">Artist</a></th>
				<th><a href="/?sort=album">Album</a></th>
				<th><a href="/?sort=year">Year</a></th>
				<th><a href="/?sort=length">Length</a></th>
			</tr>
			{{range .}}
			<tr>
				<td>{{.Title}}</td>
				<td>{{.Artist}}</td>
				<td>{{.Album}}</td>
				<td>{{.Year}}</td>
				<td>{{.Length}}</td>
			</tr>
			{{end}}
	</body>
	</html>
`))

// if homepage => no sort
func handler(w http.ResponseWriter, r *http.Request) {
	switch r.URL.Query().Get("sort") {
	case "title":
		sorter.Click(Title)
	case "artist":
		sorter.Click(Artist)
	case "album":
		sorter.Click(Album)
	case "year":
		sorter.Click(Year)
	case "length":
		sorter.Click(Length)
	}

	sort.Sort(sorter)

	page.Execute(w, tracks) // "tracks" becomes "." inside template
}

func main() {
	http.HandleFunc("/", handler)
	log.Println("Open http://localhost:8080")
	log.Fatal(http.ListenAndServe(":8080", nil))
}
