package main

import (
	"fmt"
	"os"
	"sort"
	"text/tabwriter"
	"time"
)

type Track struct {
	Title  string
	Artist string
	Album  string
	Year   int
	Length time.Duration
}

// List of songs
var tracks = []*Track{
	{"Go", "Delilah", "From the Roots Up", 2012, length("3m38s")},
	{"Go", "Moby", "Moby", 1992, length("3m37s")},
	{"Go Ahead", "Alicia Keys", "As I Am", 2007, length("4m36s")},
	{"Ready 2 Go", "Martin Solveig", "Smash", 2011, length("4m24s")},
}

// NEW: what column we click
type Column int

const (
	Title Column = iota
	Artist
	Album
	Year
	Length
)

func length(s string) time.Duration {
	dur, err := time.ParseDuration(s)
	if err != nil {
		panic(err)
	}
	return dur
}

func printTracks(tracks []*Track) {
	const format = "%v\t%v\t%v\t%v\t%v\t\n"
	tw := new(tabwriter.Writer).Init(os.Stdout, 0, 8, 2, ' ', 0)
	fmt.Fprintf(tw, format, "Title", "Artist", "Album", "Year", "Length")
	fmt.Fprintf(tw, format, "-----", "------", "-----", "----", "------")
	for _, t := range tracks {
		fmt.Fprintf(tw, format, t.Title, t.Artist, t.Album, t.Year, t.Length)
	}
	// format table and print to screen
	tw.Flush()
}

// NEW: wrapper around what will complies with Interface and passed to "sort()"
type customSort struct {
	tracks []*Track
	// every time Click() was called, we put an Order to this slice
	order []Column
}

// NEW: additional function to ADD ORDER with specific Column when user Clicks to a Column
// Note: element 0 = highest priority = most recent click
func (x *customSort) Click(col Column) {
	newOrder := []Column{col}
	for _, existing := range x.order {
		// only add if Click() calls a different function than what we currently have
		if existing != col {
			newOrder = append(newOrder, existing)
		}
	}
	x.order = newOrder
}

func (x customSort) Len() int { return len(x.tracks) }
func (x customSort) Swap(i, j int) {
	x.tracks[i], x.tracks[j] = x.tracks[j], x.tracks[i]
}

// this will run through slice of Orders that were generated by Click(); generate corresponding Less() function for each Order
func (x customSort) Less(i, j int) bool {
	a := x.tracks[i]
	b := x.tracks[j]
	for _, col := range x.order {
		switch col {
		case Title:
			if a.Title != b.Title {
				return a.Title < b.Title
			}
		case Artist:
			if a.Artist != b.Artist {
				return a.Artist < b.Artist
			}
		case Album:
			if a.Album != b.Album {
				return a.Album < b.Album
			}
		case Year:
			if a.Year != b.Year {
				return a.Year < b.Year
			}
		case Length:
			if a.Length != b.Length {
				return a.Length < b.Length
			}
		}
	}
	return false
}

func main() {
	fmt.Println("Original")
	printTracks(tracks)

	// Wrapper around []*Track
	sorter := customSort{
		tracks: tracks,
	}
	// User clicks Columns
	sorter.Click(Year)
	sorter.Click(Artist)

	// Actual sort
	sort.Sort(sorter)

	fmt.Println("\nClick order: Year->Artist")
	fmt.Println("Priority: Artist->Year")
	printTracks(tracks)
}
